apiVersion: nap.nupi.ai/v1alpha1
kind: Plugin
type: pipeline-cleaner
metadata:
  name: Default pipeline cleaner
  namespace: ai.nupi
  slug: pipeline-cleaner-default
  version: 0.0.1
spec:
  main: main.js
